version: "3.1"

services:
  tailscale:
    image: tailscale/tailscale
    container_name: tailscale
    privileged: true
    hostname: DockerServer
    volumes:
       - /var/lib:/var/lib
       - /dev/net/tun:/dev/net/tun
    cap_add:
       - net_admin
       - sys_module
    command: tailscaled
    network_mode: host
    restart: unless-stopped
    