volumes:
  mysqldb:
  ghost:

networks:
  database:

services:
  ghost:
    image: ghost:5-alpine
    container_name: ghost
    environment:
      database__client: mysql
      database__connection__host: mysql
      database__connection__user: ${DBUGHOST}
      database__connection__password: ${DBPGHOST}
      database__connection__database: ${DBGHOST}
      url: http://localhost:8080
    volumes:
      - ghost:/var/lib/ghost/content
    ports:
      - 8080:2368
    restart: always
    links:
      - mysql
    depends_on:
      - mysql
    networks:
      - database
  
    mysql:
    image: mysql
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${PASSSQL}
    volumes:
      - mysqldb:/var/lib/mysql
    networks:
      - database