services:
  mysql:
    image: mysql
    container_name: mysql
    hostname: db
    environment:
      - MYSQL_ROOT_PASSWORD=${PASSSQL}
    volumes:
      - mysqldb:/var/lib/mysql
    networks:
      - database

  memos:
    image: neosmemo/memos:stable
    container_name: memos
    volumes:
      - memos:/var/opt/memos
    ports:
      - 5230:5230
    init: true
    environment:
      MEMOS_DRIVER: mysql
      MEMOS_DSN: '${DBUMEMOS}:${DBPMEMOS}@tcp(db)/${DBMEMOS}'
    restart: unless-stopped
    links:
      - mysql
    depends_on:
      - mysql
    networks:
      - database

volumes:
  mysqldb:
    external: true
  memos:
    external: true

networks:
  database:
    external: true
