services:
  plex:
    image: linuxserver/plex:latest
    container_name: plex
    hostname: plex
    mem_limit: 3g
    cpu_shares: 1024
    security_opt:
      - no-new-privileges:true
    volumes:
      - ${DATA}plex:/config
      - ${MEDIA}:/media
    environment:
      - PUID=0
      - PGID=0
      - TZ=${TZ}
      - VERSION=docker
    network_mode: host
    restart: unless-stopped

  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    hostname: qbittorrent
    mem_limit: 3g
    cpu_shares: 1024
    security_opt:
      - no-new-privileges:false
    ports:
      - 8103:8103
      - 6881:6881
      - 6881:6881/udp
    volumes:
      - ${DATA}qbittorrent:/config
      - ${DESCARGAS}:/downloads/torrents
    environment:
      - PUID=0
      - PGID=0
      - TZ=${TZ}
      - WEBUI_PORT=8103
    restart: always

  jackett:
    image: linuxserver/jackett:latest
    container_name: jackett
    hostname: jackett
    init: true
    mem_limit: 3g
    cpu_shares: 1024
    security_opt:
      - no-new-privileges:false
    ports:
      - 9117:9117
    volumes:
      - ${DATA}jackett/data:/config
      - ${DATA}jackett/blackhole:/downloads
    environment:
      - PUID=0
      - PGID=0
      - TZ=${TZ}
      - AUTO_UPDATE=true
    restart: always

  flaresolverr:
    image: flaresolverr/flaresolverr
    container_name: flaresolverr
    hostname: flaresolverr
    init: true
    mem_limit: 3g
    cpu_shares: 1024
    security_opt:
      - no-new-privileges:false
    ports:
      - 8191:8191
    environment:
      - LOG_LEVEL=info
      - TZ=${TZ}
    restart: always

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    hostname: sonarr
    init: true
    mem_limit: 3g
    cpu_shares: 1024
    security_opt:
      - no-new-privileges:false
    ports:
      - 8989:8989
    volumes:
      - ${DATA}sonarr/data:/config
      - ${SERIES}:/tv
      - ${DESCARGAS}:/downloads/torrents
    environment:
      - PUID=0
      - PGID=0
      - TZ=${TZ}
    restart: always

  bazarr:
    image: linuxserver/bazarr:latest
    container_name: bazarr
    hostname: bazarr
    init: true
    mem_limit: 3g
    cpu_shares: 1024
    security_opt:
      - no-new-privileges:false
    ports:
      - 6767:6767
    volumes:
      - ${DATA}bazarr/config:/config
      - ${SERIES}:/tv
    environment:
      - PUID=0
      - PGID=0
      - TZ=${TZ}
    restart: always

  tinymediamanager:
    image: romancin/tinymediamanager:latest
    container_name: tinymediamanager
    hostname: bazarr
    init: true
    mem_limit: 3g
    cpu_shares: 1024
    security_opt:
      - no-new-privileges:true
    ports:
      - 5800:5800
    volumes:
      - ${DATA}tinymediamanager:/config
      - ${DESCARGAS}:/media
    environment:
      - GROUP_ID=0
      - USER_ID=0
      - TZ=${TZ}
    restart: always
